# Generated by Django 3.0.3 on 2020-03-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
