# Generated by Django 3.0.3 on 2020-03-20 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoting',
            name='election',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='election.Electioninfo'),
        ),
    ]
