# Generated by Django 3.0.3 on 2020-03-21 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20200320_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservoting',
            name='election',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='election.Election'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='election',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='election.Electioninfo'),
        ),
    ]
