# Generated by Django 3.0.2 on 2020-01-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_number', models.IntegerField(default=0, max_length=12)),
                ('name', models.CharField(default=None, max_length=10)),
                ('address', models.CharField(default=None, max_length=30)),
                ('father_name', models.CharField(default=None, max_length=10)),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('dob', models.DateField(default=None)),
                ('district', models.CharField(default=None, max_length=15)),
                ('taluk', models.CharField(default=None, max_length=15)),
                ('phone_number', models.IntegerField(default=0)),
                ('photo', models.ImageField(default=None, upload_to='')),
            ],
        ),
    ]
