# Generated by Django 3.0.2 on 2020-01-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authenticate_vote', '0002_auto_20200118_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='adhar_number',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.IntegerField(default=None, max_length=10),
        ),
    ]
