# Generated by Django 3.0.2 on 2020-01-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authenticate_vote', '0003_auto_20200118_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
