
# Generated by Django 3.0.2 on 2020-01-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authenticate_vote', '0004_auto_20200118_1559'),
        ('user_authenticate_vote', '0003_auto_20200118_1556'),
    ]

    operations = [
    ]
