# Generated by Django 3.0.3 on 2020-02-16 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authenticate_vote', '0007_userdetails_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='father_name',
            new_name='careof',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='taluk',
        ),
    ]
