# Generated by Django 3.0.3 on 2020-03-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authenticate_vote', '0009_auto_20200319_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='face_encodings',
            field=models.BinaryField(null=True),
        ),
    ]
