# Generated by Django 3.0.3 on 2020-02-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(default=None)),
                ('gender', models.CharField(default=None, max_length=1)),
                ('name', models.CharField(default=None, max_length=25)),
                ('careof', models.CharField(default=None, max_length=25)),
                ('dist', models.CharField(default=None, max_length=36)),
                ('address', models.CharField(default=None, max_length=256)),
                ('pin', models.CharField(default=None, max_length=7)),
            ],
        ),
    ]
