# Generated by Django 3.0.3 on 2020-02-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdata',
            name='aadhar',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
