# Generated by Django 3.0.2 on 2020-01-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedetails',
            name='cand_phoneno',
            field=models.IntegerField(default=0),
        ),
    ]
