# Generated by Django 3.0.2 on 2020-01-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_vote', '0002_auto_20200118_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='election_name',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
