# Generated by Django 3.0.2 on 2020-02-01 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_vote', '0003_election_election_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cand_location', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='candidatedetails',
            name='cand_gender',
        ),
        migrations.AddField(
            model_name='candidatedetails',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=1),
        ),
        migrations.AlterField(
            model_name='candidatedetails',
            name='cand_phoneno',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='candidatedetails',
            name='candidate_name',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AddField(
            model_name='election',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='candidate_vote.Location'),
        ),
    ]
