# Generated by Django 3.0.2 on 2020-02-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_vote', '0004_auto_20200201_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='cand_location',
            new_name='location',
        ),
    ]
