# Generated by Django 3.0.3 on 2020-03-19 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidate_vote', '0005_auto_20200201_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVoting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_vote.Electioninfo')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
